app = "Likelihood of H5N1 WHO Public Health Emergency by 2030"

kill_signal = "SIGINT" # Signal used to gracefully stop the app
kill_timeout = 5 # Time in seconds to give app after a kill signal

[build]
builder = "paketobuildpacks/builder:base" # Uses buildpacks to build your Python app

[env]
PORT = "8080" # Sets the PORT environment variable to 8080.

[experimental]
auto_rollback = true # Enables automatic rollback in case of deployment failures

[[services]]
internal_port = 8080 # The internal port that your app listens on
protocol = "tcp"

[[services.ports]]
port = 80 # Public HTTP port 80
handlers = ["http"]

[[services.ports]]
port = 443 # Public HTTPS port 443
handlers = ["tls", "http"]
